In [4]:
import pandas as pd

# Tools for responsible AI system development

In [ ]:
tools_list = [
    {
        "tool": "ydata_profiling",
        "principle": "baseline",
        "documentation": "https://docs.profiling.ydata.ai/latest/getting-started/concepts/",
        "codebase": "https://github.com/ydataai/ydata-profiling",
        "modality": "tabular, timeseries, text",
        "provider": "ydata",
        "domain": "all",
        "code_snippet_path": "code_snippets/ydata_profiling.py:data_profiling_eda",
        "ai_operation": ["data_profiling"],
        "article": ["10.2", "10.3"],
        "question": [
            "How many instances are there in total?",
            "What is the distribution of the target variable?",
            "How varied are the data types and sources?",
        ],
    },
    {
        "tool": "ydata_synthetic",
        "principle": "robustness",
        "documentation": "https://docs.sdk.ydata.ai/latest/synthetic_data/",
        "codebase": "https://github.com/ydataai/ydata-synthetic",
        "modality": "tabular, timeseries",
        "provider": "ydata",
        "domain": "all",
        "code_snippet_path": "code_snippets/ydata_synthetic.py:generate_synthetic_data",
        "ai_operation": ["data_preprocessing"],
        "article": ["10.5"],
        "question": [
            "Can I generate a specific number of synthetic data?",
            "What is the distribution of the target variable?",
            "Is the processing of the special category personal data variable/feature strictly necessary for bias detection / correction? Could other data (including synthetic / anonymised) fulfil it?"
        ],
    },
    {
        "tool": "mostlyai",
        "principle": "robustness",
        "documentation": "https://mostly-ai.github.io/mostlyai/usage/",
        "codebase": "https://github.com/mostly-ai/mostlyai",
        "modality": "tabular, timeseries",
        "provider": "mostlyAI",
        "domain": "classification, regression",
        "code_snippet_path": "code_snippets/mostlyai.py:generate_synthetic_data",
        "ai_operation": ["data_preprocessing"],
        "article": ["10.5"],
        "question": [
            "How many instances are there in total?",
            "What is the distribution of the target variable?",
            ""
            "Is the processing of the special category personal data variable/feature strictly necessary for bias detection / correction? Could other data (including synthetic / anonymised) fulfil it?"
        ],
    },
    {
        "tool": "fairlearn",
        "principle": "fairness",
        "documentation": "https://fairlearn.org/main/quickstart.html",
        "codebase": "",
        "modality": "tabular",
        "provider": "microsoft",
        "domain": "tabular",
        "code_snippet_path": "code_snippets/fairlearn.py:post_inference_transformations_threshold_EO",
        "ai_operation": ["post_inference_transformations"],
        "article": ["10.5"],
        "question": [
            "Does the model satisfy demographic parity, equal opportunity, or equalized odds across sensitive groups?",
            "Which subgroup has the largest disparity in true positive, false positive, or selection rates?",
            "How does model accuracy change after applying fairness constraints?",
            "What fairness-utility trade-off do we get when switching between different mitigation constraints?",
            "Does threshold optimization reduce disparities while keeping acceptable performance?",
            "Are fairness improvements consistent across validation folds or temporal slices?"
        ],
    },
    {
        "tool": "holisticai",
        "principle": "fairness, robustness, explainability, privacy",
        "documentation": "https://holisticai.readthedocs.io/en/latest/getting_started/quickstart.html",
        "codebase": "https://github.com/holistic-ai/holisticai",
        "modality": "tabular",
        "provider": "holisticai",
        "domain": "classification, regression",
        "code_snippet_path": "",
        "ai_operation": ["data_processing", "model_training", "model_evaluation", "post_inference_transformation"],
        "article": ["10.2", "10.3"],
        "question": [
            "How fair is my model across protected groups (e.g., demographic parity, equal opportunity, equalized odds)?",
            "Which subgroup suffers the largest performance gap and on which metric?",
            "How does bias change before vs. after applying a mitigation strategy?",
            "Which fairness mitigation method (pre-, in-, post-processing) gives the best utility-fairness trade-off?",
            "Are feature attributions consistent across groups, or do explanations vary unfairly?",
            "Which features contribute most to potentially discriminatory outcomes?",
            "Is the model robust to small perturbations or distribution shifts in input data?",
            "How much performance degradation occurs under adversarial or noisy conditions?",
            "Does synthetic or transformed data reduce bias without introducing privacy risk?",
            "Are there privacy leakage risks (e.g., re-identification or memorization signals) in model behavior?",
            "What thresholds should be set to balance fairness constraints and business performance targets?",
            "Which fairness metrics are most stable across cross-validation folds or time windows?"
        ],
    },
    {
        "tool": "variationist",
        "principle": "fairness",
        "documentation": "https://variationist.readthedocs.io/en/latest/intro.html",
        "codebase": "https://github.com/dhfbk/variationist",
        "modality": "text",
        "provider": "dhfbk",
        "domain": "chatbot, text generation, text classification, text summarization",
        "code_snippet_path": "code_snippets/variationist.py:run_inspector",
        "ai_operation": ["data_profiling"],
        "article": ["10.2", "10.3"],
        "question": ["How can I analyze and explore language variation and bias in written language data?", 
                     "Which are the mos frequent and common terms in our dataset?"],
    },
    {
        "tool": "witwidget",
        "principle": "explainability, fairness, uncertainty",
        "documentation": "https://pair-code.github.io/what-if-tool/",
        "codebase": "https://github.com/pair-code/what-if-tool",
        "modality": "tabular, image, text",
        "provider": "Google",
        "domain": "classification, regression",
        "code_snippet_path": "code_snippets/witwidget.py:explainability_fairness_what_if_analysis",
        "ai_operation": ["data_profiling", "model_evaluation"],
        "article": ["10.2", "10.3"],
        "question": [
            "What changes to an individual data point's features would cause the model to produce a different prediction (counterfactual analysis)?",
            "How does model performance differ across subgroups defined by a sensitive attribute (e.g., gender, age, race)?",
            "Which features have the greatest influence on the model's prediction for a specific instance?",
            "How do two or more models compare in terms of predictions and performance on the same dataset?",
            "What is the model's confidence score for a given prediction, and how does it vary across the data?",
            "Are there systematic patterns in the model's errors across different demographic slices?",
            "What is the trade-off between fairness metrics (e.g., demographic parity vs. equal opportunity) when adjusting the classification threshold?",
            "Which data points are closest to the decision boundary and therefore most uncertain?",
        ],
    },
    {
        "tool": "giskard",
        "principle": "all",
        "documentation": "https://docs.giskard.ai/en/latest/getting_started/quickstart/index.html",
        "codebase": "",
        "modality": "tabular, text, vision",
        "provider": "giscard",
        "domain": "",
        "code_snippet_path": "",
        "ai_operation": ["model_evaluation", "model_monitoring"],
        "article": ["10.2", "10.3"],
        "question": [
            "What are the highest-risk model failures detected by automated ML tests on this dataset?",
            "Can we detect prompt injection, hallucination, or harmful output risks for LLM use cases?",
            "Which features or patterns are driving unstable or brittle predictions?",
            "How does model quality change between training, validation, and production-like data?",
            "What tests should be added to prevent regressions before deployment?"
        ],
    },
    {
        "tool": "aif360",
        "principle": "fairness",
        "documentation": "https://github.com/Trusted-AI/AIF360/tree/main",
        "codebase": "",
        "modality": "tabular",
        "provider": "IBM",
        "domain": "",
        "code_snippet_path": "",
        "ai_operation": ["data_processing", "model_training", "model_evaluation", "post_inference_transformation"],
        "article": ["10.2", "10.3"],
        "question": [
            "What is the level of statistical bias in the dataset across protected attributes?",
            "How fair are model outcomes across groups according to common fairness metrics?",
            "Which pre-processing or in-processing mitigation reduces bias the most?",
            "How much predictive performance is affected by fairness mitigation?",
            "Do fairness metrics remain stable across different decision thresholds?",
            "Are there intersectional groups with significantly worse outcomes?"
        ],
    },
    {
        "tool": "interpret",
        "principle": "explainability",
        "documentation": "https://interpret.ml/docs/",
        "codebase": "",
        "modality": "text, image, audio, video, tabular",
        "provider": "microsoft",
        "domain": "",
        "code_snippet_path": "",
        "ai_operation": ["data_processing", "model_evaluation", "post_inference_transformation"],
        "article": ["14"],
        "question": [
            "Which features globally contribute most to model predictions?",
            "How can we explain an individual prediction to an end user?",
            "Are explanations consistent across sensitive or business-critical groups?",
            "Which interactions between features are driving model behavior?",
            "Can an interpretable glassbox model match blackbox performance?",
            "Which samples are hard to explain and may indicate model instability?"
        ],
    },
    {
        "tool": "aix360",
        "principle": "explainability",
        "documentation": "https://github.com/Trusted-AI/AIX360",
        "codebase": "",
        "modality": "text, image, audio, video, tabular",
        "provider": "IBM",
        "domain": "",
        "code_snippet_path": "",
        "ai_operation": ["data_processing", "model_evaluation", "post_inference_transformation"],
        "article": ["14"],
        "question": [
            "Which local and global explanation methods best describe this model's decisions?",
            "How faithful are generated explanations to the underlying model behavior?",
            "Are explanations robust under small input perturbations?",
            "Do explanations reveal proxy variables for sensitive attributes?",
            "How can we compare explanation quality across multiple XAI techniques?",
            "Which model decisions remain unexplained and require further review?"
        ],
    },
    {
        "tool": "lime",
        "principle": "explainability",
        "documentation": "https://github.com/marcotcr/lime",
        "codebase": "",
        "modality": "text, image, audio, video, tabular",
        "provider": "lime",
        "domain": "",
        "code_snippet_path": "",
        "ai_operation": ["model_evaluation", "model_monitoring", "post_inference_transformation"],
        "article": ["14"],
        "question": [
            "Which input features most influenced this single prediction?",
            "How stable are local explanations when we slightly perturb the same instance?",
            "Do similar instances receive similar local explanations?",
            "Which words, pixels, or variables are driving a negative vs positive outcome?",
            "Can local explanations help identify spurious correlations in the model?",
            "How do LIME explanations compare with SHAP or other explainers on the same sample?"
        ],
    },
    {
        "tool": "adversarial-robustness-toolbox",
        "principle": "robustness",
        "documentation": "https://github.com/Trusted-AI/adversarial-robustness-toolbox?tab=readme-ov-file",
        "codebase": "https://github.com/Trusted-AI/adversarial-robustness-toolbox",
        "modality": "text, image, audio, video, tabular",
        "provider": "IBM",
        "domain": "",
        "code_snippet_path": "",
        "ai_operation": ["model_training", "model_evaluation", "model_monitoring", "post_inference_transformation"],
        "article": ["14"],
        "question": [
            "How vulnerable is the model to evasion, poisoning, or extraction attacks?",
            "Which adversarial attack types most reduce model performance?",
            "What minimum perturbation is required to change model predictions?",
            "Does adversarial training improve robustness without major accuracy loss?",
            "Which classes or subgroups are most sensitive to adversarial examples?",
            "How robust is the model under realistic noise and corruption settings?"
        ],
    },
    {
        "tool": "aequitas-fairlib",
        "principle": "fairness",
        "documentation": "https://pikalab-unibo-students.github.io/master-thesis-dizio-ay2324/",
        "codebase": "https://github.com/pikalab-unibo-students/master-thesis-dizio-ay2324/tree/master",
        "modality": "tabular",
        "provider": "aequitas",
        "domain": "classification, regression",
        "code_snippet_path": "",
        "ai_operation": ["data_preprocessing", "model_training", "model_evaluation"],
        "article": ["10.2", "10.3"],
        "question": ["What demographic information and domain is the dataset aiming to represent?", 
                     "What is the minimum sample size to represent the population sufficiently and significantly? ",
                     "What is the distribution of the target variable?",
                     "Is the dataset representative of the target population or domain?",
                     "Is the dataset sufficiently large to capture the variability and complexity of the underlying phenomena?",
                     "Are there enough samples from minority or underrepresented groups to avoid biases and ensure fairness? "],
    },
    {
        "tool": "evidently",
        "principle": "baseline, robustness",
        "documentation": "https://github.com/evidentlyai/evidently",
        "codebase": "https://github.com/evidentlyai/evidently",
        "modality": "tabular, text, embeddings",
        "provider": "evidently.ai",
        "code_snippet_path": "code_snippets/evidently.py:data_profiling_detect_data_drift",
        "ai_operation": ["data_validation", "model_monitoring", "production_data_monitoring"],
        "article": ["10.1", "10.2", "10.3"],
        "question": [
            "Can you create a report about the level of data drift for the given reference and target data?"
            "How many features of each type do we have?",
            "How many features are (mostly) missing or constant?",
            "How are the features distributed?",
            "Which features are strongly correlated?",
            "Are two datasets similar?",
            "If something has changed, what exactly?",
        ],
    },
    {
        "tool": "nannyml",
        "principle": "baseline, robustness",
        "documentation": "https://nannyml.readthedocs.io/en/stable/quick.html",
        "codebase": "https://github.com/nannyml/nannyml",
        "modality": "tabular, text, embeddings",
        "provider": "nannyml",
        "code_snippet_path": "code_snippets/nannyml.py:model_monitoring_concept_drift",
        "ai_operation": ["data_validation", "model_monitoring", "production_data_monitoring"],
        "question": [
            "Is the pattern learned by the model still applicable?",
            "Has the decision boundary changed?",
            "What is the magnitude of the concept drift?",
            "What is the impact of concept drift on model performance?",
            "What is the impact of covariate shift on model performance?",
            "Has the relationship between the target variable and the model inputs changed?",
            "What is the expected performance on unseen data or data with different distributions?",
        ],
    },
    {
        "tool": "alibi-detect",
        "principle": "robustness",
        "documentation": "https://docs.seldon.ai/alibi-detect",
        "codebase": "https://github.com/SeldonIO/alibi-detect",
        "modality": "text, image, audio, video, tabular, time series",
        "provider": "SeldonIO",
        "domain": "regression, chatbot, object detection",
        "code_snippet_path": "",
        "ai_operation": "",
        "question": ["How different two datasets are?", 
                     "Is there any data drift between two datasets?",
                     "Does the data contain any outliers?",
                     "Does the data contain any adversarial examples?",
                     ],
    },
    {
        "tool": "nemo-evaluator",
        "principle": "baseline",
        "documentation": "https://docs.nvidia.com/nemo/evaluator/latest/about/index.html",
        "codebase": "https://github.com/NVIDIA-NeMo/Evaluator.git",
        "modality": "text",
        "provider": "nvidia",
        "domain": "LLM-based Agent, text classification, text summarization, text generation, RAG, speech-to-text",
        "code_snippet_path": "",
        "ai_operation": "",
        "question": [
            "How can I compare the performance of different LLM models on text generation, text classification, text summarization, text generation, RAG, and speech-to-text tasks?",
        ],
    },
    {
        "tool": "trulens",
        "principle": "baseline",
        "documentation": "https://www.trulens.org/getting_started/",
        "codebase": "https://github.com/truera/trulens/",
        "modality": "text",
        "provider": "trulens",
        "domain": "LLM-based Agent, text classification, text summarization, text generation, RAG, speech-to-text",
        "code_snippet_path": "",
        "ai_operation":  ["model_evaluation", "model_monitoring"],
        "question": [
            "How can I compare the performance of different LLM models on text generation, text classification, text summarization, text generation, RAG, and speech-to-text tasks?",
        ],
    },
    {
        "tool": "ragas",
        "principle": "baseline",
        "documentation": "https://docs.ragas.io/en/stable/",
        "codebase": "https://github.com/vibrantlabsai/ragas",
        "modality": "text",
        "provider": "SeldonIO",
        "domain": "LLM-based Agent, text classification, text summarization, text generation, RAG, speech-to-text",
        "code_snippet_path": "",
        "ai_operation": ["model_evaluation", "model_monitoring"],
        "question": [
            "How can I compare the performance of different LLM models on text generation, text classification, text summarization, text generation, RAG, and speech-to-text tasks?",
        ],
    },
    {
        "tool": "unsloth",
        "principle": "optimization",
        "documentation": "https://unsloth.ai/docs/get-started/fine-tuning-llms-guide",
        "codebase": "https://github.com/unslothai/unsloth",
        "modality": "text",
        "provider": "unslothai",
        "domain": "fine tuning, optimized training, fast inference",
        "code_snippet_path": "",
        "ai_operation": ["model_training"],
        "question": [
            "How can I fine-tune and optimize the performance of different LLM models for specific tasks?",
        ],
    },
    {
        "tool": "great_expectations",
        "principle": "baseline",
        "documentation": "https://docs.greatexpectations.io/docs/",
        "codebase": "https://github.com/great-expectations/great_expectations",
        "modality": "tabular",
        "provider": "great_expectations",
        "domain": "classification, regression",
        "code_snippet_path": "code_snippets/great_expectations.py:data_validation_values_between",
        "ai_operation": ["data_validation"],
        "question": [
            "What volume of data is necessary for the development of the AI system, keeping in mind the data minimisation principle?",
            "How many instances are there in total?",
            "What is the distribution of the target variable?",
            "How many missing values do we have in each feature?",
            "How many features do we have in total?",
            "Are there any significant outliers or anomalies?",
        ],
    }
]
tools_principles_df = pd.DataFrame(
    tools_list,
    columns=[
        "tool",
        "principle",
        "documentation",
        "codebase",
        "domain",
        "modality",
        "provider",
        "code_snippet_path",
        "ai_operation",
        "article",
        "question",
    ],
)
# modality: tabular, text, image, audio, video
# applicative domain: chatbot, classification, regression, object detection, text classification, text summarization, text generation, RAG, LLM-based Agent, speech-to-text
#tools_principles_df = tools_principles_df.assign(principle=tools_principles_df["principle"].str.split(",")).explode("principle").reset_index(drop=True)
#tools_principles_df = tools_principles_df.assign(modality=tools_principles_df["modality"].str.split(",")).explode("modality").reset_index(drop=True)
tools_principles_df.to_csv("tools_principles_catalog.csv", index=False)
tools_principles_df.head()

,tool,principle,documentation,codebase,domain,modality,provider,code_snippet_path,ai_operation,article,question
0,ydata_profiling,baseline,https://docs.profiling.ydata.ai/latest/getting...,https://github.com/ydataai/ydata-profiling,all,"tabular, timeseries, text",ydata,code_snippets/ydata_profiling.py:data_profilin...,[data_profiling],"[10.2, 10.3]","[How many instances are there in total?, What ..."
1,ydata_synthetic,robustness,https://docs.sdk.ydata.ai/latest/synthetic_data/,https://github.com/ydataai/ydata-synthetic,all,"tabular, timeseries",ydata,code_snippets/ydata_synthetic.py:generate_synt...,[data_preprocessing],[10.5],[Can I generate a specific number of synthetic...
2,mostlyai,robustness,https://mostly-ai.github.io/mostlyai/usage/,https://github.com/mostly-ai/mostlyai,"classification, regression","tabular, timeseries",mostlyAI,code_snippets/mostlyai.py:generate_synthetic_data,[data_preprocessing],[10.5],"[How many instances are there in total?, What ..."
3,fairlearn,fairness,https://fairlearn.org/main/quickstart.html,,tabular,tabular,microsoft,code_snippets/fairlearn.py:post_inference_tran...,[post_inference_transformations],[10.5],"[Does the model satisfy demographic parity, eq..."
4,holisticai,"fairness, robustness, explainability, privacy",https://holisticai.readthedocs.io/en/latest/ge...,https://github.com/holistic-ai/holisticai,"classification, regression",tabular,holisticai,,"[data_processing, model_training, model_evalua...","[10.2, 10.3]",[How fair is my model across protected groups ...

# OECD catalog of tools and metrics for trustworthy AI

## Fairness tools

In [11]:
fairness_tools_df = pd.read_csv("fairness_tools.csv")
fairness_tools_df

,Unnamed: 0,Title,Website,Github,Gitlab,Hugging Face,Package,Slack
0,0,Eticas Bias,https://eticas.ai/itaca/,https://github.com/eticasai/eticas-audit,NaN,NaN,NaN,NaN
1,1,Mindgard,https://mindgard.ai/,https://github.com/Mindgard/cli,NaN,NaN,https://pypi.org/project/mindgard/,NaN
2,2,PyRIT,https://github.com/Azure/PyRIT,https://github.com/Azure/PyRIT,NaN,NaN,https://pypi.org/project/pyrit/,NaN
3,3,garak,https://garak.ai/,https://github.com/leondz/garak,https://garak.ai/,NaN,https://pypi.org/project/garak/,NaN
4,4,zamba,NaN,https://github.com/drivendataorg/zamba,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
149,149,augmix_tf2,NaN,https://github.com/AakashKumarNain/AugMix_TF2,NaN,NaN,NaN,NaN
150,150,auditor,NaN,https://github.com/ModelOriented/auditor,NaN,NaN,NaN,NaN
151,151,artificial-life-simulator,NaN,https://github.com/BLayman/Artificial-Life-Sim...,NaN,NaN,NaN,NaN
152,152,androidtensorflowmachinelearningexample,NaN,https://github.com/amitshekhariitbhu/AndroidTe...,NaN,NaN,NaN,NaN
153,153,android-tensorflow-lite-example,NaN,https://github.com/amitshekhariitbhu/Android-T...,NaN,NaN,NaN,NaN

## Fairness metrics

In [15]:
fairness_metrics_df = pd.read_csv("fairness_metrics.csv")
fairness_metrics_df.head()

,Unnamed: 0,Title,Website,Main reference,Github stars,Github forks,Citations,References,Gitlab,Hugging Face
0,0,Equal performance,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6...,NaN,0.0,0.0,0.0,NaN,NaN,NaN
1,1,Recall,https://en.wikipedia.org/wiki/Precision_and_re...,NaN,0.0,0.0,0.0,NaN,NaN,NaN
2,2,Gender-based Illicit Proximity Estimate (GIPE),https://arxiv.org/abs/2006.01938,NaN,0.0,0.0,0.0,NaN,NaN,NaN
3,3,F-score,https://en.wikipedia.org/wiki/F-score,NaN,0.0,0.0,0.0,NaN,NaN,NaN
4,4,Exact Match,https://huggingface.co/spaces/evaluate-metric/...,NaN,0.0,0.0,0.0,NaN,NaN,NaN

Fairness Metrics
- Demographic parity
- Equalized odds
- Equality of opportunity

## Robustness

In [18]:
robustness_metrics_df = pd.read_csv("robustness_metrics.csv")
robustness_metrics_df.head()

,Unnamed: 0,Title,Website,Main reference,Github stars,Github forks,Citations,References,Gitlab,Hugging Face
0,0,Accuracy,https://en.wikipedia.org/wiki/Accuracy_and_pre...,NaN,0.0,0.0,0.0,NaN,https://huggingface.co/papers/2302.04166,NaN
1,1,Mahalanobis Distance,http://library.isical.ac.in:8080/xmlui/bitstre...,NaN,0.0,0.0,0.0,NaN,https://huggingface.co/papers/2302.04166,NaN
2,2,Mean Intersection over Union (IoU),https://giou.stanford.edu/,NaN,0.0,0.0,0.0,NaN,https://huggingface.co/papers/2302.04166,NaN
3,3,Time until Adversary’s Success,https://www.semanticscholar.org/paper/An-Analy...,NaN,0.0,0.0,0.0,NaN,https://huggingface.co/papers/2302.04166,NaN
4,4,Receiver Operating Characteristic Curve (ROC) ...,https://developers.google.com/machine-learning...,NaN,0.0,0.0,0.0,NaN,NaN,NaN

# Explainability

🟢 𝐒𝐇𝐀𝐏 (𝐒𝐇𝐚𝐩𝐥𝐞𝐲 𝐀𝐝𝐝𝐢𝐭𝐢𝐯𝐞 𝐞𝐱𝐏𝐥𝐚𝐧𝐚𝐭𝐢𝐨𝐧𝐬)
Most popular method and often does a decent job.

The SHAP algorithm considers additive feature importance for explaining the collective contribution of the underlying model features.

🟢 𝐋𝐈𝐌𝐄 (𝐋𝐨𝐜𝐚𝐥 𝐈𝐧𝐭𝐞𝐫𝐩𝐫𝐞𝐭𝐚𝐛𝐥𝐞 𝐌𝐨𝐝𝐞𝐥-𝐚𝐠𝐧𝐨𝐬𝐭𝐢𝐜 𝐄𝐱𝐩𝐥𝐚𝐧𝐚𝐭𝐢𝐨𝐧𝐬)
Similar to SHAP, LIME is a model-agnostic explanation technique.

It is used for interpreting models by learning a local model around the predictions, which means it is a “local” model explainer.

🟢 𝐄𝐥𝐢5 (𝐄𝐱𝐩𝐥𝐚𝐢𝐧 𝐋𝐢𝐤𝐞 𝐈’𝐦 𝐅𝐢𝐯𝐞)
Eli5 is a Python XAI library for debugging, inspecting, and explaining ML classifiers.

It explains black-box models in the most simplified format and supports a wide range of ML modeling frameworks, e.g., scikit-learn and Keras.

🟢 𝐀𝐈 𝐄𝐱𝐩𝐥𝐚𝐢𝐧𝐚𝐛𝐢𝐥𝐢𝐭𝐲 𝟑𝟔𝟎 (𝐀𝐈𝐗𝟑𝟔𝟎)
AIX360 is an IBM-developed open-source library designed to enhance model interpretability across multiple data types, including tabular, text, image, and time-series data.

It provides a diverse set of explanation techniques and evaluation metrics, helping users assess model transparency and debug complex AI systems.

🟢 𝐈𝐧𝐭𝐞𝐫𝐩𝐫𝐞𝐭𝐌𝐋
Microsoft's InterpretML is a powerful Python package offering both interpretable "glassbox" models and explainers for "blackbox" models.

It helps machine learning practitioners understand model behavior using cutting-edge interpretability 
methods, promoting responsible AI development.